kind: pipeline
type: docker
name: Push Image

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
      - promote

steps:
  # Docker image
  - name: docker-image
    image: plugins/docker
    settings:
      username:
          from_secret: docker-user
      password:
          from_secret: docker-key
      repo: randomman552/one-pager
      tags:
          - latest
  
  # Reporting
  - name: build-reporter
    image: randomman552/drone-build-reporter
    depends_on:
      - docker-image
    settings:
      gotify_token:
        from_secret: gotify-token
      gotify_url:
        from_secret: gotify-url
