kind: pipeline
type: docker
name: Push Image

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request

steps:
  - name: Build and Push Image
    image: plugins/docker
    environment:
      DOCKER_USER:
        from_secret: docker-user
    settings:
        username:
            from_secret: docker-user
        password:
            from_secret: docker-key
        repo: ${DOCKER_USER}/one-pager
        tags:
            - latest